#!/bin/sh

mkdir -p initramfs/{bin,sbin,etc,proc,sys,usr/bin,usr/sbin}

# Put whatever you want into initramfs

# create initramfs compressed file.
find . | cpio -o -H newc | gzip > ../initramfs.img.gz
cd ..

# Copy to boot partition.
cp initramfs.img.gz <boot partition path>
rm -rf ./initramfs.img.gz
